title: "Tiutle Sangwon Hwang"
author: "Author Sangwon Hwang"
description: ""

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 1                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

url: https://sangwon-hwang.github.io
baseurl: #

# Theme settings
show_excerpts: false          # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: false            # enables dark mode
dark_header: false           # uses dark header whether dark_theme is enabled or not
minimal_theme: false         # radically minimalistic theme
mathjax: true

navigation:                  # show navigation links in the header
  - index.html
  - about.md
  - publications.md

#icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
#  envelope: ""
#  github: ""
#  feed: ""

comments:                    # embed disqus or isso comments
  disqus: "blog-19lbnvrzrc"
#  isso: ""

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
encoding: "utf-8"

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
